// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrGEdWKxNGHiGTp94qOWH4ERwsIEATf4c',
    appId: '1:182383081018:android:6003a723b4ab936b552703',
    messagingSenderId: '182383081018',
    projectId: 'apk-kampus',
    storageBucket: 'apk-kampus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABjZT_VzOFd0ylX4oNq7-ueD-HIfTbVYI',
    appId: '1:182383081018:ios:c64ce0d1af9b772b552703',
    messagingSenderId: '182383081018',
    projectId: 'apk-kampus',
    storageBucket: 'apk-kampus.appspot.com',
    iosBundleId: 'com.example.apkKampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABjZT_VzOFd0ylX4oNq7-ueD-HIfTbVYI',
    appId: '1:182383081018:ios:c64ce0d1af9b772b552703',
    messagingSenderId: '182383081018',
    projectId: 'apk-kampus',
    storageBucket: 'apk-kampus.appspot.com',
    iosBundleId: 'com.example.apkKampus',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6xPwUIb92wpOYVQ-rTm1p-eb80UQo8Dg',
    appId: '1:182383081018:web:d3768498fde7ca32552703',
    messagingSenderId: '182383081018',
    projectId: 'apk-kampus',
    authDomain: 'apk-kampus.firebaseapp.com',
    storageBucket: 'apk-kampus.appspot.com',
    measurementId: 'G-YWX4VFLC4S',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6xPwUIb92wpOYVQ-rTm1p-eb80UQo8Dg',
    appId: '1:182383081018:web:ee3c6d8113d976f1552703',
    messagingSenderId: '182383081018',
    projectId: 'apk-kampus',
    authDomain: 'apk-kampus.firebaseapp.com',
    storageBucket: 'apk-kampus.appspot.com',
    measurementId: 'G-RM3CN3MJ20',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
